image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_PROD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CONTAINER_TEST_IMAGE || true
    - docker build --pull --cache-from $CONTAINER_TEST_IMAGE --tag $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE app:latest
    - |
      set -e
      set -o pipefail
      cd api_tests
      docker-compose run tests || true
      docker-compose run --entrypoint /bin/cat app /app/test-results.xml > ../test-results.xml
  artifacts:
    reports:
      junit:
        - test-results.xml
        - api_tests/results/api-test-results.xml

release-dev:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DEV_IMAGE
    - docker push $CONTAINER_DEV_IMAGE
  only:
    - master

release-prod:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    refs:
      - tags
